### ISSUE TITLE
I have a problem when study antlr4 suggestions step by step;

### ISSUE THREAD

**Issue by minesunny** [DanielBV/antlr4-shulk#1]
I am studying and wish to complete my own lsp by reading your post and your code;now, I am reading [third post](https://www.abstractsyntaxseed.com/blog/antlr4-autocomplete-library/rules) and stuck in before step`Precedence in rules`; I am debuging a case (Test left-recursion) in my code and compare with yours. and I find a problem,In js code ,it has two same transitions in one state, but not in java;
it happens in whileloop Thirty-first;
<img width="459" alt="image" src="https://github.com/DanielBV/antlr4-shulk/assets/98507458/255b9578-08ab-4d35-8817-66a45b285985">

<img width="1523" alt="image" src="https://github.com/DanielBV/antlr4-shulk/assets/98507458/77634755-1ba9-4aa5-a4c3-d317cf2f660b">

**Comment by DanielBV** [comment]
Hi, I'm glad to know there's interest in the topic and my posts.

I can explain why JS has two transitions, but I have no idea why Java has only one. Each language target might have small implementation differences. Since both transitions seem to be the same maybe Java optimizes the ATN. Is this difference causing a different output? 

About why there are two, I made a quick debug and it seems that those two transitions are in the state `1`, which is the `RuleStopState` of `expr`. At the beginning of the post I explained that since the `RuleStopState` doesn't know which is the following state it has to point to all posibilities
```js
await givenGrammar(`
      first: called 'A';
      second: called 'B';
      third: called 'C';

      called: 'F';`)
.whenInput("F").thenExpect(["A", "B", "C"]);
``` 
leads to 
![ATN diagram](https://www.abstractsyntaxseed.com/static/images/antlr4-autocomplete/ATN_Rules_caller.png)

Now, when you see a left recursion like
```antlr
 expr: expr (MULT|DIV) expr
      | expr (PLUS|MINUS) expr
      | ID;
```
ANTLR4 removes it, transforming it into something like:
```antlr
expr[int pr] : id
               ( {4 >= $pr}? '*' expr[5]
               | {3 >= $pr}? '+' expr[4]
               )*
             ;
``` 
So we have two internal `expr` calls inside an asterisk block. And when both `expr` finishes, each one goes to the `BlockEndState` which in this case is state `14`, hence two transitions. And afterwards it checks if it should repeat the block again or end it. 

To confirm this theory I added a third subrule
```antlr
 expr: expr (MULT|DIV) expr
      | expr (PLUS|MINUS) expr
      | expr (ID) expr
      | ID;
``` 
And now the state `1` has three epsilon transition pointing to the same `BlockEndState`

I hope this was helpful

**Comment by minesunny** [comment]
> Hi, I'm glad to know there's interest in the topic and my posts.
> 
> I can explain why JS has two transitions, but I have no idea why Java has only one. Each language target might have small implementation differences. Since both transitions seem to be the same maybe Java optimizes the ATN. Is this difference causing a different output?
> 
> About why there are two, I made a quick debug and it seems that those two transitions are in the state `1`, which is the `RuleStopState` of `expr`. At the beginning of the post I explained that since the `RuleStopState` doesn't know which is the following state it has to point to all posibilities
> 
> ```js
> await givenGrammar(`
>       first: called 'A';
>       second: called 'B';
>       third: called 'C';
> 
>       called: 'F';`)
> .whenInput("F").thenExpect(["A", "B", "C"]);
> ```
> 
> leads to ![ATN diagram](https://camo.githubusercontent.com/65d06a5cb50699b3ab6edf6b93d72aabe3152a57b2e5d4f3e8d84df9e11dac7d/68747470733a2f2f7777772e616273747261637473796e746178736565642e636f6d2f7374617469632f696d616765732f616e746c72342d6175746f636f6d706c6574652f41544e5f52756c65735f63616c6c65722e706e67)
> 
> Now, when you see a left recursion like
> 
> ```antlr
>  expr: expr (MULT|DIV) expr
>       | expr (PLUS|MINUS) expr
>       | ID;
> ```
> 
> ANTLR4 removes it, transforming it into something like:
> 
> ```antlr
> expr[int pr] : id
>                ( {4 >= $pr}? '*' expr[5]
>                | {3 >= $pr}? '+' expr[4]
>                )*
>              ;
> ```
> 
> So we have two internal `expr` calls inside an asterisk block. And when both `expr` finishes, each one goes to the `BlockEndState` which in this case is state `14`, hence two transitions. And afterwards it checks if it should repeat the block again or end it.
> 
> To confirm this theory I added a third subrule
> 
> ```antlr
>  expr: expr (MULT|DIV) expr
>       | expr (PLUS|MINUS) expr
>       | expr (ID) expr
>       | ID;
> ```
> 
> And now the state `1` has three epsilon(ε) transition pointing to the same `BlockEndState`
> 
> I hope this was helpful

Thanks for your explain,this is very helpful;and I can tell you that it doesn't cause a different result between js and java;
